version: "3.7"
services:
  mypostgres2:
    image: postgres
    container_name: mypostgres2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticketing
    networks:
      - webnet
    volumes:
      - initdb:/var/lib/postgres/data
  ticketing:
    build: .
    container_name: ticketingcondep
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres2
    networks:
      - webnet
volumes:
  initdb:
networks:
  webnet:
    driver: bridge
